apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-backend
spec:
  hosts:
  - istio-backend
  http:
  - route:
    - destination:
        host: istio-backend
        subset: v1
      weight: 50
    - destination:
        host: istio-backend
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-backend-destination
spec:
  host: istio-backend
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
